### ISSUE TITLE
! LaTeX Error: Option clash for package beamerfontthemeserif.

### ISSUE THREAD

**Issue by mojtabaahmadi2020tl** [kvafa/xepersian#1]
## Check/indicate
- [ ] Relevant to the `bidi` package
- [ ] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{beamer}

\usefonttheme{serif}

\usepackage{xepersian} % version 24.1
\settextfont{Yas}
\setdigitfont{Yas}


\begin{document}

\begin{frame}
تست
\[
\sum_{i=1}^n i=\frac{n(n+1)}{2}
\]
\end{frame}

\end{document}
```
## Expected behavior

درود جناب وفا، به گزینه 
stillsansserifmath
 نیاز ندارم.

## Log and PDF files 

[test_beamer_xepersain.pdf](https://github.com/kvafa/xepersian/files/8769312/test_beamer_xepersain.pdf)
[test_beamer_xepersain.log](https://github.com/kvafa/xepersian/files/8769313/test_beamer_xepersain.log)

**Comment by kvafa** [comment]
Thanks for your bug report. `beamer` is now supported so you should not load the serif font theme as it is activated by the `xepersian` package.

**Comment by mojtabaahmadi2020tl** [comment]
با تشکر از زحمات، جناب وفا بجای گزینه stillsansserifmath از \usefonttheme{professionalfonts}
 استفاده شود بنظرم بهتره.

**Comment by kvafa** [comment]
The reason why I decided to have sans serif math was the fact that serif math looked ugly since it uses the alphabets from Persian font selected via `\setextfont` control sequence; additionally, sans serif math is the default math font in beamer. If people wish, they can load professional fonts themselves as the package should not force any thing to the user. I hope that it makes sense.
