### ISSUE TITLE
\savebox  does not correctly when xepersian loads via cls file.

### ISSUE THREAD

**Issue by javadr** [kvafa/xepersian#10]
## Brief outline of the issue
I have a `cls` file that loads `xepersian` package at the end of the preamble with the aid of `biditools`.  In this file I want to reuse an image for several positions, thus using a LaTeX `savebox` is desired.  Unfortunately, when the saved box has been reused the position of the saved image is not correct and it will typeset outside the box. 

## Check/indicate
- [ ] Relevant to the `bidi` package
- [X] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [X] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

The `testclass` definition:
```tex
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{testclass}
\RequirePackage{graphicx}
\RequirePackage{biditools}
\ProcessOptions
\LoadClass{article}

\bidi@AtEndPreamble{%
    \RequirePackage{xepersian}%
    \settextfont{Yas}%
}

\newsavebox\test
\savebox\test{\fbox{\includegraphics[width=1.2cm]{{images/logo}}}}
```

Its usage:
```tex
\documentclass{testclass}

\begin{document}
\usebox\test
\end{document}
```
## Expected behavior
The following picture shows the issue and the expected behavior. 
![Screenshot from 2022-06-03 11-06-53](https://user-images.githubusercontent.com/1178221/171800634-3c0b6d05-399c-4126-9eb7-b05a49b5b2d1.png)

## Log and PDF files 
[test.log](https://github.com/kvafa/xepersian/files/8830080/test.log)
[test.pdf](https://github.com/kvafa/xepersian/files/8830081/test.pdf)

**Comment by kvafa** [comment]
Thanks for your bug report. This is not a bug. You are using the control sequence `\savebox` so bidi changes are not applied as you are saving the content of the box using its old definition. The following minimal example demonstrates the issue.

````tex
\documentclass{article}
\usepackage{graphicx}
\newsavebox\test
\savebox\test{\fbox{\includegraphics[width=1.2cm]{{example-image}}}}
\usepackage[RTLdocument]{bidi}
\begin{document}
\usebox\test
\end{document}
````
To resolve this, you need to use control sequence `\savebox` after loading the `bidi` package (in your case, after loading the `xepersian` package).
````tex
\documentclass{article}
\usepackage{graphicx}
\newsavebox\test
\usepackage[RTLdocument]{bidi}
\savebox\test{\fbox{\includegraphics[width=1.2cm]{{example-image}}}}
\begin{document}
\usebox\test
\end{document}
````
