### ISSUE TITLE
localise is not working with `tagging` package

### ISSUE THREAD

**Issue by 1995parham** [kvafa/xepersian#15]
## Check/indicate
- [ ] Relevant to the `bidi` package
- [x] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [x] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}            % or some other class

\usepackage{tagging}
\usepackage[%
    localise
]{xepersian}
\settextfont{IRXLotus}

%\usetag{answer}
\newenvironment{answer}
{
  \taggedblock{answer}
  \vspace{5mm}
  \color{WildStrawberry}
  \rule{2cm}{0.5pt}\\
  \متن‌سیاه{پاسخ.}\\
}
{
  \endtaggedblock
}

\eqenvironment{پاسخ}{answer}

\begin{document}

\begin{پاسخ}
  من یک پاسخ هستم
\end{پاسخ}

\end{document}

```

## Expected behavior

When there is no answer tag, the answer block shouldn't be rendered, but because the `\eqenvironment{پاسخ}{answer}` we got an error.

**Comment by 1995parham** [comment]
Dear @kvafa . I think this issue didn't resolve, if you agree we can reopen this issue again.

**Comment by kvafa** [comment]
I can see that you have changed your minimal example! That is not how it is supposed to work. If you are using the localized environment, then your `\begin` and `\end` should also match. The following example shows that there is no issue.

````tex
\documentclass{article}            % or some other class

\usepackage{tagging}
\usepackage[%
    localise
]{xepersian}
\settextfont{IRXLotus}

%\usetag{answer}
\newenvironment{answer}
{
  \taggedblock{answer}
  \vspace{5mm}
  \color{WildStrawberry}
  \rule{2cm}{0.5pt}\\
  \متن‌سیاه{پاسخ.}\\
}
{
  \endtaggedblock
}

\eqenvironment{پاسخ}{answer}

\شروع{نوشتار}

\شروع{پاسخ}
  من یک پاسخ هستم
\پایان{پاسخ}

\پایان{نوشتار}
````

**Comment by 1995parham** [comment]
Yes, you are right. it works, thanks again.
