### ISSUE TITLE
Typesetting numbers in math mode with pgf-pie

### ISSUE THREAD

**Issue by bahman-mirzakhani** [kvafa/xepersian#22]
## Brief outline of the feature request
Irregular output of decimal numbers in the chart. Maybe it is better to write them in a inline math mode.

## Check/indicate
- [ ] Relevant to the `bidi` package
- [x] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [x] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}

\usepackage{pgf-pie}
% =
%\usepackage{tikz}
%\usetikzlibrary{pie}

\usepackage{xepersian}
\settextfont{IRXLotus}
\setmathdigitfont{IRXLotus}

% In the `tikzlibrarypie.code.tex` file,
%  the command used to display the numbers is defined with the name `\pgfpie@numbertext`.
% We can change the numbers on the chart to math mode.
% If we make this change, everything will be OK.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\makeatletter
\bidi@patchcmd{\pgfpie@numbertext}%
	{\pgfpie@beforenumber#1\pgfpie@afternumber}%
	{\pgfpie@beforenumber$#1$\pgfpie@afternumber}{}{}
\makeatother
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Note:
% I want you to make this change with the lovely `xepersian` package please.

\begin{document}
		
	\tikz\pie[polar, radius=2]{15.5/A,30/B,19.5/C,35/D};
	
\end{document}
```

## Expected behavior
I want to typeset numbers in math environment (inline math).

[test.log](https://github.com/kvafa/xepersian/files/9120379/test.log)
[test.pdf](https://github.com/kvafa/xepersian/files/9120381/test.pdf)

**Comment by kvafa** [comment]
I had a look at this just now and I think the package provides the key value `before number` and `after number` for this particular purpose.

````tex
\documentclass{article}
\usepackage{pgf-pie}
\usepackage{xepersian}
\settextfont{IRXLotus}
\setmathdigitfont{IRXLotus}
\begin{document}
		
\tikz\pie[polar, radius=2,before number=$,after number={\%$}]{15.5/A,30/B,19.5/C,35/D};
	
\end{document}
````

Therefore, I have decided to close this feature request without any changes to the `xepersian` package.
