### ISSUE TITLE
Right alignment of text in columns environment while using beamer

### ISSUE THREAD

**Issue by Hosein-Rahnama** [kvafa/xepersian#27]
It seems that text is not properly aligned within `columns` environment, while using the `beamer` class. Here is a minimal example showing the issue.

```
\documentclass{beamer}

\usepackage{xepersian}
\settextfont{Persian Modern}

\begin{document}

\begin{frame}
\frametitle{راست‌چین شدن محیط ستون‌ها توسط \lr{\XePersian}}
\begin{columns}
\begin{column}{0.5\textwidth}
ستون اول
\begin{itemize}
\item
آیتم اول
\item 
آیتم دوم
\end{itemize}
\end{column}
\begin{column}{0.5\textwidth}
ستون دوم
\begin{enumerate}
\item 
شمارشی اول
\item
شمارشی دوم
\end{enumerate}
\end{column}
\end{columns}
\end{frame}

\end{document}
```
[sample.pdf](https://github.com/kvafa/xepersian/files/13567533/sample.pdf)

**Comment by ghost** [comment]
Thanks for your bug report. I have fixed this issue and will upload the new version of the `bidi` package on January 1, 2025 to CTAN. If this addresses your issue, then please consider closing this issue.
