### ISSUE TITLE
error \color<>{} in beamer 

### ISSUE THREAD

**Issue by mojtabaahmadi2020tl** [kvafa/xepersian#3]
## Check/indicate
- [ ] Relevant to the `bidi` package
- [ ] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{beamer}

\usepackage{xepersian}
\settextfont{Yas}


\begin{document}

\begin{frame}
این یک تست است. 

{\color<2-3>{blue} 
این متن به رنگ آبی است در اسلاید 2 و 3، در غیراینصورت مشکی.}
\end{frame}

\end{document}
```
## Expected behavior
! Package xcolor Error: Undefined color `<'.
See the xcolor package documentation for explanation.
Type H <return> for immediate help.

درود جناب وفا، قبلا چند مشکل را اینجا نوشتم
https://github.com/mojtabaahmadi2020tl

https://github.com/mojtabaahmadi2020tl/beamer_color/blob/main/beamer_color.tex

## Log and PDF files 

[test_color_beamer.log](https://github.com/kvafa/xepersian/files/8770737/test_color_beamer.log)
[test_color_beamer.pdf](https://github.com/kvafa/xepersian/files/8770739/test_color_beamer.pdf)

**Comment by kvafa** [comment]
I have fixed the error in version 37.8 of the `bidi` package and the following example should give you the correct output.

````tex
\documentclass{beamer}

\usepackage{xepersian}
\settextfont{IRXLotus}


\begin{document}

\begin{frame}
این یک تست است. 

\leavevmode{\color<2-3>{blue} 
این متن به رنگ آبی است در اسلاید 2 و 3، در غیراینصورت مشکی.}
\end{frame}

\end{document}
````

**Comment by mojtabaahmadi2020tl** [comment]
درود جناب وفا، با تشکر از زحمات

غیر از دستور \color دستورات دیگه هم نیاز به \leavevmode هست.
امکانش هست که \leavevmode رو در دستورات تعریف شده قرار داد که کاربر نیاز به نوشتن آن نباشد.

آیا ایمیلتون tex-persian@vafa.ac‬ فعال هست که فایل کمینه بفرستم مشاهده کنید.

با تشکر

**Comment by kvafa** [comment]
Thanks for your reply. It is not wise to add `\leavevmode` as this might break other parts of beamer which works without any issues in right to left mode. To report any bugs, please only use GitHub and not my email address. It is very hard for me to manage issues sent to my email.
