### ISSUE TITLE
Using LTRfoonote within theorem-like environments colored by tcolorbox

### ISSUE THREAD

**Issue by Hosein-Rahnama** [kvafa/xepersian#32]
I usually use `tcolorbox` package for coloring my theorem-like environments. Recently, I encountered a problem while I was trying to use footnotes within these environments. The default behavior is that the footnotes are placed at the end of the box while I want them be placed at the end of the page. It would be nice to have an option for the `LTRfootnote` that allows one to choose between these two different behaviors. The following links on parsilatex.com also show that this feature has been requested several times. A solution is also suggested in Link 2.

[Link 1](https://qa.parsilatex.com/38953/%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%D9%BE%D8%A7%D9%88%D8%B1%D9%82%DB%8C-%D9%87%D8%A7-%D8%AF%D8%B1-%D9%85%D8%AD%DB%8C%D8%B7-%D9%87%D8%A7%DB%8C-%D8%AC%D8%B9%D8%A8%D9%87-%D8%A7%DB%8C)
[Link 2](https://qa.parsilatex.com/36627/)
[Link 3](http://qa.parsilatex.com/36623/)

**Comment by ghost** [comment]
I'm afraid the `bidi` / `xepersian` packages are not the right place to implement these features. I can certainly proceed and implement what you are asking but then I would be changing `tcolorbox` behavior and this would introduce incompatibility with `tcolorbox` package when used without loading `bidi` / `xepersian` packages.

However, if the `tcolorbox` package implement this feature for `\footnote`, I will be more than happy to extend `\LTRfootnote` and `\RTLfootnote` to match it.

If this addresses your issue, then please consider closing this issue.

**Comment by ghost** [comment]
Also, note that the solution provided by @bahman-mirzakhani is limited and has a serious flaw. His solution is to save footnotes and insert them at the end of the environment. This solution is perfectly fine if you do not allow page breaks. However, if you use `breakable` option and the text inside your `tcolorbox` environment spans more than a page, then your footnotes will appear on the page where `tcolorbox` environment ends and not on the pages where footnotes naturally are.

**Comment by ghost** [comment]
> Also, note that the solution provided by @bahman-mirzakhani is limited and has a serious flaw. His solution is to save footnotes and insert them at the end of the environment. This solution is perfectly fine if you do not allow page breaks. However, if you use `breakable` option and the text inside your `tcolorbox` environment spans more than a page, then your footnotes will appear on the page where `tcolorbox` environment ends and not on the pages where footnotes naturally are.

The `footnotehyper` package also suffers from this same limitation.
